default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: admin
      password: saSST2184
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production